# Deploy to all environments

name: Deploy Web API to All Environments
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install dependencies
        run: dotnet restore ./SampleWebApi/SampleWebApi.csproj
  
      - name: Build
        run: dotnet build ./SampleWebApi/SampleWebApi.csproj --configuration Release --no-restore
  
      - name: Publish
        run: dotnet publish ./SampleWebApi/SampleWebApi.csproj --configuration Release --no-build --output ./publish --no-build

      - name: Upload publish output
        uses: actions/upload-artifact@v4
        with:
          name: webapi-artifacts
          path: ./publish

  deploy-dev:
    permissions:
      contents: none

    runs-on: ubuntu-latest
    needs: build
    environment: Development

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapi-artifacts

      - name: Deploy to Dev Azure Web App
        id: deploy-to-webapp-dev
        uses: azure/webapps-deploy@v2
        with:
          app-name: samplewebapi
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish/SampleWebApi.zip

