## Build and deploy webapp
# This workflow will build and publish the webapp to the gh-pages branch

name: Deploy Webapp to Dev Environment

on:
  workflow_dispatch:

permissions:
  contents: read

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install dependencies
        run: dotnet restore ./SampleWebApi/SampleWebApi.csproj
  
      - name: Build
        run: dotnet build ./SampleWebApi/SampleWebApi.csproj --configuration Release --no-restore
  
      - name: Publish
        run: dotnet publish ./SampleWebApi/SampleWebApi.csproj --configuration Release --no-build --output ./publish --no-build

      - name: Upload publish output
        uses: actions/upload-artifact@v2
        with:
          name: webapi-artifact
          path: ./publish

  deploy:
    permissions:
      contents: none

    strategy:
      matrix:
        environment: [Development, Production]
  
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapi-artifact
     
      - name: Set environment variables
        run: echo "AZURE_WEBAPP_PUBLISH_PROFILE=${{ secrets[format('AZURE_WEBAPP_PUBLISH_PROFILE_{0}', matrix.environment)] }}" >> $GITHUB_ENV

      #- name: Deploy to ${{ matrix.environment }}
      #  id: deploy-to-webapp
        # uses: azure/webapps-deploy@v2
        # with:
        #   app-name: samplewebapi
        #   slot-name: ${{ matrix.environment }}
        #   publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
        #   package: ./publish/SampleWebApi.zip
    
